name: mgent
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.15
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.15
  - python_abi=3.10
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - accelerate==1.1.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - anthropic==0.38.0
    - anyio==4.6.2.post1
    - argparse==1.4.0
    - async-timeout==4.0.3
    - attrs==24.2.0
    - beautifulsoup4==4.12.3
    - bitsandbytes==0.44.1
    - blobfile==3.0.0
    - brotli==1.1.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - dataclasses-json==0.6.7
    - datasets==3.1.0
    - dill==0.3.8
    - distro==1.9.0
    - filelock==3.16.1
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - gdown==5.2.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google==3.0.0
    - greenlet==3.1.1
    - groq==0.12.0
    - grpcio==1.67.1
    - h11==0.14.0
    - httpcore==1.0.6
    - httpx==0.27.2
    - httpx-sse==0.4.0
    - huggingface-hub==0.27.1
    - idna==3.10
    - importlib-resources==6.4.5
    - inflate64==1.0.0
    - inquirerpy==0.3.4
    - jinja2==3.1.4
    - jiter==0.7.0
    - joblib==1.4.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - langchain==0.3.14
    - langchain-community==0.3.14
    - langchain-core==0.3.29
    - langchain-huggingface==0.1.2
    - langchain-text-splitters==0.3.5
    - langgraph==0.2.61
    - langgraph-checkpoint==2.0.9
    - langgraph-sdk==0.1.48
    - langsmith==0.2.10
    - lxml==5.3.0
    - markdown==3.7
    - markupsafe==3.0.2
    - marshmallow==3.24.1
    - msgpack==1.1.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - multivolumefile==0.2.3
    - mypy-extensions==1.0.0
    - networkx==3.4.2
    - nltk==3.9.1
    - numpy==1.26.0
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.1.105
    - nvidia-nvtx-cu12==12.1.105
    - ollama==0.3.3
    - openai==0.27.6
    - orjson==3.10.13
    - pandas==1.5.3
    - peft==0.2.0
    - pfzy==0.3.4
    - pillow==11.0.0
    - pip==24.3.1
    - propcache==0.2.0
    - protobuf==5.28.3
    - py7zr==0.22.0
    - pyarrow==18.0.0
    - pybcj==1.0.2
    - pycryptodomex==3.21.0
    - pydantic==2.10.5
    - pydantic-core==2.27.2
    - pydantic-settings==2.7.1
    - pylatexenc==2.10
    - pyppmd==1.1.0
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-liquid==1.12.1
    - pytz==2024.2
    - pyyaml==6.0.2
    - pyzstd==0.16.2
    - regex==2023.12.25
    - replicate==0.23.1
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - rouge-score==0.1.2
    - safetensors==0.4.5
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sentence-transformers==3.3.1
    - sentencepiece==0.2.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.6
    - sqlalchemy==2.0.36
    - sympy==1.13.1
    - tenacity==9.0.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - texttable==1.7.0
    - threadpoolctl==3.5.0
    - tiktoken==0.8.0
    - tokenizers==0.21.0
    - torch==2.5.1+cu121
    - torchaudio==2.5.1+cu121
    - torchvision==0.20.1+cu121
    - tqdm==4.64.1
    - transformers==4.48.0
    - triton==3.1.0
    - typing-inspect==0.9.0
    - tzdata==2024.2
    - urllib3==2.2.3
    - werkzeug==3.1.3
    - xxhash==3.5.0
    - yarl==1.17.1
prefix: /home/komal.kumar/.conda/envs/mgent
