name: mgent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.15
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - pip
  - setuptools
  - wheel
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib-inline
  - psutil
  - traitlets
  - tornado
  - pygments
  - xz
  - zlib
  - readline
  - ncurses
  - tk
  - sqlite
  - libffi
  - openssl
  - typing_extensions
  - pexpect
  - pip:
    - absl-py==2.1.0
    - accelerate==1.1.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - anthropic==0.38.0
    - huggingface-hub==0.27.1
    - transformers==4.48.0
    - torchvision==0.20.1
    - torchaudio==2.5.1
    - tensorboard
    - tqdm
prefix: /Users/komal.kumar/miniconda3/envs/mgent
